name: Android CD

on:
  push:
    branches: [ release ]

concurrency:
  group: cd-release
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode keystore (base64)
        run: |
          mkdir -p app/keystore
          echo "${UPLOAD_KEYSTORE_B64}" | base64 -d > app/keystore/nearbynote-release.jks
        env:
          UPLOAD_KEYSTORE_B64: ${{ secrets.UPLOAD_KEYSTORE }}

      - name: Write gradle.properties for CI
        run: |
          cat > gradle.properties <<'EOF'
          android.useAndroidX=true
          android.enableJetifier=true
          kotlin.code.style=official
          android.nonTransitiveRClass=true
          org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
          EOF

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build signed AAB
        env:
          ORG_GRADLE_PROJECT_MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
          ORG_GRADLE_PROJECT_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          ORG_GRADLE_PROJECT_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: ./gradlew --no-daemon --stacktrace :app:bundlePublicRelease

      - name: Sanity check AAB exists
        run: |
          ls -al app/build/outputs/bundle/publicRelease
          test -f app/build/outputs/bundle/publicRelease/app-public-release.aab

      - name: Upload to Google Play (Internal)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.pjh.nearbynote
          releaseFiles: app/build/outputs/bundle/publicRelease/app-public-release.aab
          track: internal
          status: completed
          changesNotSentForReview: true

      - name: Keep artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-public-release
          path: |
            app/build/outputs/bundle/publicRelease/app-public-release.aab
            app/build/outputs/mapping/publicRelease/mapping.txt